import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Book your haircutter!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to this incredible online booking system!
        </h1>
      </main>

      <footer>
        <a>Powered by TEAM NINJA</a>
      </footer>
    </div>
  )
}

export default Home